@startuml
'https://plantuml.com/class-diagram

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

enum LightColor <<enum>>
{
    GREEN
    ORANGE
    RED
}

interface LightStrategy <<interface>>
{
    + {abstract} getNextColor(lightColor:LightColor) : LightColor
}

class Main
{
    + {static} main(String[])
}

class TrafficLight
{
    - lit : boolean
    - lightColor : LightColor
    - oldLightColor : LightColor
    - lightStrategy : LightStrategy

    + TrafficLight()
    + changeColor() : void
    + changeState() : void
    + getLightColor() : LightColor
}

class FranceStrategy implements LightStrategy
{
    + FranceStrategy()
    + getNextColor(lightColor:LightColor) : LightColor
}

class GermanyStrategy implements LightStrategy
{
    + GermanyStrategy(oldLightColor:LightColor)
    + getNextColor(lightColor:LightColor) : LightColor
    + getOldLightColor() : LightColor
    + setOldLightColor() : void
}

TrafficLight o-> LightStrategy
TrafficLight *-left> LightColor
GermanyStrategy *-> LightColor
Main .> TrafficLight : <<use>>
Main .> FranceStrategy : <<use>>
Main .> GermanyStrategy : <<use>>

@enduml