@startuml
'https://plantuml.com/class-diagram

@startuml

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide enum methods

class Bar {
    - {static} instance:Bar

    - Bar()
    + leave(customer:Customer)
    + fire(bartender:Bartender)
    + createMug(capacity:Integer)
    + {static} getInstance():Bar
}

Bar <- Bar

@enduml

@enduml